# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Page title')),
                ('keywords', models.TextField(blank=True, null=True, verbose_name='Keywords')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('og_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Open Graph Title')),
                ('og_description', models.TextField(blank=True, null=True, verbose_name='Open Graph Description')),
                ('og_image_url', models.URLField(blank=True, null=True, verbose_name='Open Graph URL')),
                ('object_pk', models.PositiveIntegerField(editable=False)),
                ('content_type', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'SEO object',
                'verbose_name_plural': 'SEO objects',
            },
        ),
        migrations.CreateModel(
            name='SeoURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Page title')),
                ('keywords', models.TextField(blank=True, null=True, verbose_name='Keywords')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('og_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Open Graph Title')),
                ('og_description', models.TextField(blank=True, null=True, verbose_name='Open Graph Description')),
                ('og_image_url', models.URLField(blank=True, null=True, verbose_name='Open Graph URL')),
                ('url', models.CharField(help_text='Or beginning URL part beginning and ending with "/"', max_length=255, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'SEO path',
                'verbose_name_plural': 'SEO path',
            },
        ),
        migrations.CreateModel(
            name='SeoURLMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('http_equiv', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('charset', models.CharField(blank=True, max_length=10, null=True)),
                ('seo_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metatags', to='seo.SeoURL')),
            ],
            options={
                'verbose_name': 'SEO path metatag',
                'verbose_name_plural': 'SEO path metatag',
            },
        ),
    ]
